"""Domain schemas package."""

from .portfolio import Holding, PortfolioDecision, PortfolioSnapshot, UserProfile
from .proposal import (
    ExecutionPlan,
    ProposalMarketContext,
    ProposalResponse,
    ProposalSignalSummary,
    ProposedAction,
)
from .report import (
    FeaturedIdeaReport,
    FeaturedSectorIdea,
    FeaturedStockIdea,
    MarketOverviewReport,
    PricePlan,
    WatchlistReportItem,
    WatchlistSummaryReport,
)
from .research import (
    BacktestMetrics,
    BacktestResponse,
    BacktestTrade,
    EquityPoint,
    MarketPoint,
    MarketSnapshotResponse,
    ScreenCandidate,
    ScreenResponse,
    StrategyDetailResponse,
    StrategyItem,
    StrategyListResponse,
    SummaryResponse,
    TickerAnalysisResponse,
    TickerAnalysisStructured,
)
from .signals import (
    AggregatedCandidate,
    CandidateSignalView,
    SignalRunRequest,
    SignalRunResponse,
    SignalSynthesis,
    StrategySignal,
)

__all__ = [
    "AggregatedCandidate",
    "BacktestMetrics",
    "BacktestResponse",
    "BacktestTrade",
    "CandidateSignalView",
    "EquityPoint",
    "ExecutionPlan",
    "FeaturedIdeaReport",
    "FeaturedSectorIdea",
    "FeaturedStockIdea",
    "Holding",
    "MarketPoint",
    "MarketOverviewReport",
    "MarketSnapshotResponse",
    "PortfolioDecision",
    "PricePlan",
    "PortfolioSnapshot",
    "ProposalMarketContext",
    "ProposalResponse",
    "ProposalSignalSummary",
    "ProposedAction",
    "ScreenCandidate",
    "ScreenResponse",
    "SignalRunRequest",
    "SignalRunResponse",
    "SignalSynthesis",
    "StrategyDetailResponse",
    "StrategyItem",
    "StrategyListResponse",
    "StrategySignal",
    "SummaryResponse",
    "TickerAnalysisResponse",
    "TickerAnalysisStructured",
    "UserProfile",
    "WatchlistReportItem",
    "WatchlistSummaryReport",
]
